name: Build Android APK Otomatis

on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Buat file gradlew (Versi 8.4)
        working-directory: ./android
        run: gradle wrapper --gradle-version 8.4

      - name: Beri izin eksekusi pada Gradle
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Build APK (Debug)
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Simpan APK agar bisa diunduh
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-zanhub-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
